### DISCUSSION TITLE
Help Remediating: S3 Buckets should enforce encryption of data transfers using Secure Sockets Layer (SSL)

### DISCUSSION THREAD

**Discussion by createchange** [Checkmarx/kics#5546] [Q&A]
I am using KICS via Gitlab, and it is spawning a vulnerability finding for a bucket that does not have SSL transport configured.

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/29058450/176759927-f8678386-b36e-4580-9d0c-5f572e98a848.png">

I have added a statement to the policy, which adds the required rules to enforces SSL, however the finding is not remediated.

Help with adding the appropriate CloudFormation configuration is appreciated.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack for Bucket that houses  Cookbooks

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    Properties:
      BucketName: <bucket-name>
      VersioningConfiguration:
          Status: Enabled
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'AES256'

  BucketPolicy:  
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Allow access only via HTTPS
          Action: 
            - "s3:*"
          Effect: "Deny"
          Principal: "*"
          Resource:
            - arn:aws:s3:::<bucket-name>/*
            - arn:aws:s3:::<bucket-name>
          Condition:
            Bool: 
              aws:SecureTransport: "false"
        - Sid: Allow access to bucket from Sandbox sub-account
          Action: "*"
          Effect: Allow
          Resource:
            - arn:aws:s3:::<bucket-name>/*
            - arn:aws:s3:::<bucket-name>
          Principal:
            AWS: arn:aws:iam::<account-id>:root
        - Sid: Allow access to bucket from Production sub-account
          Action: "*"
          Effect: Allow
          Resource:
            - arn:aws:s3:::<bucket-name>/*
            - arn:aws:s3:::<bucket-name>
          Principal:
            AWS: arn:aws:iam::<account-id>:root
        - Sid: Allow access to bucket from NonProduction sub-account
          Action: "*"
          Effect: Allow
          Resource:
            - arn:aws:s3:::<bucket-name>/*
            - arn:aws:s3:::<bucket-name>
          Principal:
            AWS: arn:aws:iam::<account-id>:root
```

**Comment by kaplanlior** [comment]
For the condition syntax try this example:
```
            Bool:
              'aws:SecureTransport': false
```
Notice the single quotes are on the key, not the value.

More examples are available on the [query's tests](https://github.com/Checkmarx/kics/tree/master/assets/queries/cloudFormation/aws/s3_bucket_without_ssl_in_write_actions/test)

**Comment by createchange** [comment]
I appreciate you reaching back @kaplanlior. Unfortunately, that did not resolve the issue.

```yaml
...
  BucketPolicy:  
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Allow access only via HTTPS
          Action: 
            - "s3:*"
          Effect: "Deny"
          Principal: "*"
          Resource:
            - arn:aws:s3:::<bucket>/*
            - arn:aws:s3:::<bucket>
          Condition:
            Bool: 
              'aws:SecureTransport': false

...
```

<img width="297" alt="image" src="https://user-images.githubusercontent.com/29058450/176912265-3511012d-82ea-4114-8cfb-2f026ca2030e.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/29058450/176912331-acffc720-47b7-4475-be14-86cce88c3c98.png">

Is there anything else that you might be able to suggest?

Thanks!
