### ISSUE TITLE
When running scan over a big repo, kics takes too much time to print the feedback to console, so user is not aware if it is running or not

### ISSUE THREAD

**Issue by miguelfreitas93** [Checkmarx/kics#1685]
### Expected Behavior
When initially we run kics, some information should be printed to the logs, so users are aware kics is doing something (no verbose mode) and it is not stuck, such as:
- Application Name
- Version
- Flags Provided
- Technologies Identified: Dockerfile, AWS, GCP...
- Scan Progress

For Example:
```
kics - Static Code Analysis of Infrastructure as Code.
@Checkmarx
Version: 1.1.0

Flags Provided:
-p | --path -> /path

Technologies Identified:
- Dockerfile

Total Files: 1000
Total IaC Identified Files: 1
Scanning 1 out of 1 files (100%)
Scan Success !
Results:
Files scanned: 1
Parsed files: 1
Queries loaded: 728
Queries failed to execute: 0
Healthcheck Instruction Missing, Severity: LOW, Results: 2
       Dockerfile:22
      Dockerfile:1
Missing USER Instruction, Severity: HIGH, Results: 2
      Dockerfile:1
      Dockerfile:22
Access Key Is Not Rotated Within 90 Days, Severity: MEDIUM, Results: 1
     Dockerfile:1
```

### Actual Behavior
Nothing is being printed before the scan is completed

### Steps to Reproduce the Problem

  1. git clone https://github.com/Checkmarx/kics
  2. Create a docker-compose.yml file:
```yaml
version: '3'

services:
  kics:
    platform: linux
    image: checkmarx/kics:latest
    container_name: kics
    hostname: kics
    volumes:
      - ./:/path/
    build:
      context: ./
      dockerfile: Dockerfile
    command: -p /path/
```
  4. Run docker-compose up
  5. Since kics Repo contains a lot of IAC files, kics only prints feedback to the console once the scan is finished, so user is not aware what is going on before and during the scan.

### Specifications

  - Version: latest
  - Platform: linux
  - Subsystem: docker
