### ISSUE TITLE
Enable secure cross-repo PR testing with pull_request_target workflow trigger event

### ISSUE THREAD

**Issue by rogeriopeixotocx** [Checkmarx/kics#1894]
### Description
To enable us to safely run CI jobs in cross-repo PR's we should leverage the new GitHub Actions event type: `pull_request_target`

> https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target
> This event is similar to pull_request, except that it runs in the context of the base repository of the pull request, rather than in the merge commit. This means that you can more safely make your secrets available to the workflows triggered by the pull request, because only workflows defined in the commit on the base repository are run. For example, this event allows you to create workflows that label and comment on pull requests, based on the contents of the event payload.

> In order to solve this [security issues with pull_request], we’ve added a new pull_request_target event, which behaves in an almost identical way to the pull_request event with the same set of filters and payload. However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request. This means the workflow is running from a trusted source and is given access to a read/write token as well as secrets enabling the maintainer to safely comment on or label a pull request.

After taking a look at the following securitylab.github [blog post](https://securitylab.github.com/research/github-actions-preventing-pwn-requests) we decided to try the solution in the provided example:

```
    on:
      pull_request_target:
        types: [labeled]

    jobs:
      build:
        name: Build and test
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'safe to test')
```
