### ISSUE TITLE
Add/Update Docker queries to support docker-compose.yml

### ISSUE THREAD

**Issue by miguelfreitas93** [Checkmarx/kics#1981]
### Platform
docker-compose

### Provider
Docker

### Description
Kics is not able to identify things in docker-compose.yml such as:
- Healthcheck Instruction Missing
- Image Version Not Explicit
- Image Version Using Latest
- Hardcoded Secrets/passwords/keys Arg for build or Environments
- Last User is root
- ...and others

Is that possible to have them ?
Thanks!

**Comment by miguelfreitas93** [comment]
I've scanned the docker-compose.yml in kics repository.
```yml
version: "3"

services:
  kics:
    platform: linux
    image: checkmarx/kics
    container_name: kics
    hostname: kics
    volumes:
      - ./:/path/
    build:
      context: ./
      dockerfile: Dockerfile
    command: -p /path/ -v
```


It gave the following results:
```txt
kics        | Files scanned: 1
kics        | Parsed files: 1
kics        | Queries loaded: 790
kics        | Queries failed to execute: 0
kics        | ------------------------------------
kics        |
kics        | Results Summary:
kics        | HIGH: 0
kics        | MEDIUM: 0
kics        | LOW: 0
kics        | INFO: 0
kics        | TOTAL: 0
```
