### ISSUE TITLE
View SARIF results in Azure DevOps

### ISSUE THREAD

**Issue by rogeriopeixotocx** [Checkmarx/kics#2282]
### Description
To provide better integration with Azure DevOps, we're currently trying to use [SARIF viewer build tab extension](https://marketplace.visualstudio.com/items?itemName=sariftools.sarif-viewer-build-tab) in an Azure DevOps project to provide annotations to vulnerable files.
The extension seems to be having some issues rendering the [SARIF web component](https://github.com/microsoft/sarif-web-component)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/75368139/111483537-c3e7ef00-872c-11eb-8d0b-d754fbdfce53.png)

The purpose of this issue is to track the issue opened below
https://github.com/microsoft/sarif-azuredevops-extension/issues/2

**Comment by rogeriopeixotocx** [comment]
cc: @kaplanlior

**Comment by mhabegger** [comment]
see: https://github.com/microsoft/sarif-azuredevops-extension/issues/2#issuecomment-812151111

**Comment by rogeriopeixotocx** [comment]
I was finally able to render the SARIF web viewer plugin inside Azure DevOps Pipelines with the task `PublishBuildArtifacts@1`. I'll add this example to the Azure DevOps integration docs.

![image](https://user-images.githubusercontent.com/75368139/118053381-534ffe00-b37c-11eb-9def-d8b74c03b1dd.png)

```yaml
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Kics
  displayName: Kics
  jobs:
  - job: runKics
    displayName: runKics
    steps:
      - script: |
          OS=$(uname -s)
          LATEST_TAG=$(curl --silent "https://api.github.com/repos/Checkmarx/kics/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          LATEST_VERSION=${LATEST_TAG#v}
          PACKAGE_NAME=kics_${LATEST_VERSION}_${OS}_x64.tar.gz
          TARGET_DIR=/home/vsts/kics
          mkdir -p ${TARGET_DIR}
          wget -q -c https://github.com/Checkmarx/kics/releases/download/${LATEST_TAG}/${PACKAGE_NAME} -O - | tar -xz -C ${TARGET_DIR}
          echo '--- START SCANNING ---'
          ${TARGET_DIR}/kics scan --no-progress -q ${TARGET_DIR}/assets/queries -p ${PWD} -o ${PWD}/kics-results.sarif
          ls -la
      #- task: PublishPipelineArtifact@1
      #  displayName: 'SARIF Artifacts'
      #  inputs:
      #    targetPath: $(System.DefaultWorkingDirectory)/kics-results.sarif
      #    artifact: CodeAnalysisLogs
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(System.DefaultWorkingDirectory)/kics-results.sarif
          artifactName: CodeAnalysisLogs
```
