### ISSUE TITLE
FP - Passwords and Secrets in .travis.yml

### ISSUE THREAD

**Issue by rogeriopeixotocx** [Checkmarx/kics#3773]
### Expected Behavior
KICS should not find passwords and secrets results in `.travis.yml`

### Actual Behavior
KICS finds a false positive result in this [.travis.yml](https://raw.githubusercontent.com/find-sec-bugs/find-sec-bugs/master)

results:
```json
{
	"files_scanned": 1,
	"files_parsed": 1,
	"files_failed_to_scan": 0,
	"queries_total": 236,
	"queries_failed_to_execute": 0,
	"queries_failed_to_compute_similarity_id": 0,
	"queries": [
		{
			"query_name": "Passwords And Secrets In Infrastructure Code",
			"query_id": "f996f3cb-00fc-480c-8973-8ab04d44a8cc",
			"query_url": "https://kics.io/",
			"severity": "HIGH",
			"platform": "Common",
			"files": [
				{
					"file_name": ".travis.yml",
					"similarity_id": "8039a54a2c358ea934d070d7bbea941c0c3d29641074cc1dd8133d98d7a20ffb",
					"line": 4,
					"issue_type": "RedundantAttribute",
					"search_key": "cache.directories",
					"search_value": "",
					"expected_value": "Hardcoded secret key should not appear in source",
					"actual_value": "$HOME/.m2",
					"value": null
				}
			],
			"category": "Secret Management",
			"description": "Query to find passwords and secrets in infrastructure code."
		}
	],
	"scan_id": "console",
	"severity_counters": {
		"HIGH": 1,
		"INFO": 0,
		"LOW": 0,
		"MEDIUM": 0
	},
	"total_counter": 1,
	"start": "2021-06-29T09:26:36.402065+01:00",
	"end": "2021-06-29T09:26:37.711459+01:00",
	"paths": [
		".travis.yml"
	]
}

```

Sample:
```yaml
language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
# It is unlikely that OpenJDK Early Access (openjdk-ea) it will work in the near future, the ASM library supports only bytecode from official release version.
#  - openjdk-ea


#matrix:
#  allow_failures:
#    - jdk: openjdk-ea

# Activate container based infra https://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
install: mvn clean -B -V
script: mvn clean test -Pjacoco -Ptravisci -B -V


after_success:
# Codecov.io
# Report available here : https://codecov.io/gh/find-sec-bugs/find-sec-bugs
# The tests are runned with the script command (mvn clean test...)
# Docs: https://docs.codecov.io/v1.0/docs/about-the-codecov-bash-uploader
  - bash <(curl -s https://codecov.io/bash)
```

### Steps to Reproduce the Problem

1. `kics scan --path .travis.yml`
2. check results
