### ISSUE TITLE
"CloudWatch Metrics Disabled" Gives Nonsense Results

### ISSUE THREAD

**Issue by chrisoverzero** [Checkmarx/kics#4178]
### Expected Behavior

Valid alarms are recognized as valid by query "5d3c1807-acb3-4bb0-be4e-0440230feeaf".

### Actual Behavior

Alarms which do not specify the literal property "Metrics" are flagged as missing "Metrics" and as MEDIUM Vulnerabilities.

### Steps to Reproduce the Problem

1. Create an alarm which uses "MetricName", "Dimensions", and the like:

  ```yaml
  Api5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
      - Fn::ImportValue: !Sub AlertTopic-${Environment}
      AlarmDescription: !Sub Alerts when the API for ${ServiceName} starts responding with 5xx status codes.
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: ApiName
        Value: !Ref AWS::StackName
      - Name: Stage
        Value: !Ref ServerlessRestApi.Stage
      EvaluationPeriods: 1
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Period: 60
      Statistic: Sum
      Threshold: 3
      TreatMissingData: notBreaching
      Unit: Count
  ```
2. Scan that template with kics.
3. Get confused at scan results:

  ```
  CloudWatch Metrics Disabled, Severity: MEDIUM, Results: 1
  CIS ID: CIS Security - CIS Amazon Web Services Foundations Benchmark v1.4.0 - Rule 4.1
  Title: Ensure a log metric filter and alarm exist for unauthorized API calls
  Description: Real-time monitoring of API calls can be achieved by directing CloudTrail Logs to CloudWatch Logs and establishing corresponding metric filters and alarms. It is recommended that a metric filter and alarm be established for unauthorized API calls.
  
  Platform: CloudFormation
  
  	[1]: ./template.yml:166
  
  		165:     Type: AWS::CloudWatch::Alarm
  		166:     Properties:
  		167:       AlarmActions:
  ```
  
  ```json
  {
    "query_name": "CloudWatch Metrics Disabled",
    "query_id": "5d3c1807-acb3-4bb0-be4e-0440230feeaf",
    "query_url": "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html",
    "severity": "MEDIUM",
    "platform": "CloudFormation",
    "category": "Observability",
    "description": "Checks if CloudWatch Metrics is Enabled",
    "description_id": "72a550b1",
    "cis_description_id": "CIS Security - CIS Amazon Web Services Foundations Benchmark v1.4.0 - Rule 4.1",
    "cis_description_title": "Ensure a log metric filter and alarm exist for unauthorized API calls",
    "cis_description_text": "Real-time monitoring of API calls can be achieved by directing CloudTrail Logs to CloudWatch Logs and establishing corresponding metric filters and alarms. It is recommended that a metric filter and alarm be established for unauthorized API calls.\n",
    "files": [
      {
        "file_name": "./template.yml",
        "similarity_id": "710d05124c3f8a99586a8b9259710b93fa8ed2ab96eeaadb4754e8a6e3e7160c",
        "line": 166,
        "issue_type": "MissingAttribute",
        "search_key": "Resources.Api5xxAlarm.Properties",
        "search_line": 0,
        "search_value": "",
        "expected_value": "Resources.Api5xxAlarm.Properties.Metrics should be defined",
        "actual_value": "Resources.Api5xxAlarm.Properties.Metrics is undefined",
        "value": null
      }
    ]
  }
  ```

This scan seems to think that all alarms have something to do with CloudTrail? "CIS Amazon Web Services Foundations Benchmark v1.4.0 - Rule 4.1" is about having _a particular_ metric filter and alarm in place (they even give you the operative part: `{($.errorCode="*UnauthorizedOperation") || ($.errorCode="AccessDenied*")}`), not about every alarm using a property named "Metrics", as opposed to be their being specified in other ways.

### Specifications

-   Version: Keeping Infrastructure as Code Secure 1.4.2
-   Platform: CloudFormation
-   Subsystem: macOS Catalina (10.15.7), darwin_x64 (Maybe? I don't know what Subsystem is.)
