### ISSUE TITLE
Ansible analysis fails with weird OOB error

### ISSUE THREAD

**Issue by LvffY** [Checkmarx/kics#4415]
Hello

I'm trying to run a kics analysis on my Ansible repository and fall into OOB error. 

### Expected Behavior

Run the analysis correctly

### Actual Behavior

Fail with an error `panic: runtime error: slice bounds out of range [-1:]`. [Complete logs based on `--verbose --log-level=DEBUG`](https://github.com/Checkmarx/kics/files/7392344/analyse_logs.txt)

### Steps to Reproduce the Problem

(Command line arguments and flags used)

1.  File **inventories/dev/hosts**
```yaml
---
all:
  children:
    azure:
      vars:
        ansible_connection: local
      children:
        spark_on_aks:
          hosts:
            infra:
```

2.  File **group_vars/azure/vars.yml**

```yaml
---
azure:
  client_id: "{{ vault_azure_client_id }}"
  secret: "{{ vault_azure_secret }}"
  subscription_id: "{{ vault_azure_subscription_id }}"
  tenant: "{{ vault_azure_tenant }}"

resources:
  location: francecentral
  tags:
    env_name: "env_name"
  shared:
    rg_name: "shared"
  spark_on_aks:
    rg_name: "aks"
    vnet:
      name: "vnet"
      subnet_name: "subnet"
```

3. Have the playbook **create_vnet.yml**

```yaml
---
- name: Deploy Vnet for postgresql and aks connection
  hosts: infra
  environment:
    AZURE_CLIENT_ID: "{{ azure.client_id }}"
    AZURE_SECRET: "{{ azure.secret }}"
    AZURE_SUBSCRIPTION_ID: "{{ azure.subscription_id }}"
    AZURE_TENANT: "{{ azure.tenant }}"
  tasks:

    - name: "Create virtual network {{ resources.spark_on_aks.vnet.name }}"
      azure_rm_virtualnetwork:
        resource_group: "{{ resources.spark_on_aks.rg_name }}"
        name: "{{ resources.spark_on_aks.vnet.name }}"
        address_prefixes_cidr:
          - "10.1.0.0/16"
        tags:
          PROJECT: DEMONSTRATEUR
          USECASE: SPARK_ON_AKS
          ENVIRONMENT: "{{ resources.tags.env_name }}"
        state: present

    - name: "Create subnet {{ resources.spark_on_aks.vnet.subnet_name }} associate with {{ resources.spark_on_aks.vnet.name }}"
      azure_rm_subnet:
        resource_group: "{{ resources.spark_on_aks.rg_name }}"
        virtual_network_name: "{{ resources.spark_on_aks.vnet.name }}"
        name: "{{ resources.spark_on_aks.vnet.subnet_name }}"
        address_prefix_cidr: "10.1.0.0/24"
        service_endpoints:
          - service: Microsoft.SQL
        state: present
```

4.  Inside docker image `checkmarx/kics:debian` run the analysis `/app/bin/kics scan -p create_vnet.yml -o ${PWD} --report-formats json,sarif --ignore-on-exit results --verbose --log-level=DEBUG`

After more tests, it seems that the error is based on the variable `{{ resources.spark_on_aks.vnet.subnet_name }}` especially in the task name because the following playbook is analysed correctly

```yaml
---
- name: Deploy Vnet for postgresql and aks connection
  hosts: infra
  environment:
    AZURE_CLIENT_ID: "{{ azure.client_id }}"
    AZURE_SECRET: "{{ azure.secret }}"
    AZURE_SUBSCRIPTION_ID: "{{ azure.subscription_id }}"
    AZURE_TENANT: "{{ azure.tenant }}"
  tasks:

    - name: "Create virtual network {{ resources.spark_on_aks.vnet.name }}"
      azure_rm_virtualnetwork:
        resource_group: "{{ resources.spark_on_aks.rg_name }}"
        name: "{{ resources.spark_on_aks.vnet.name }}"
        address_prefixes_cidr:
          - "10.1.0.0/16"
        tags:
          PROJECT: DEMONSTRATEUR
          USECASE: SPARK_ON_AKS
          ENVIRONMENT: "{{ resources.tags.env_name }}"
        state: present

#    - name: "Create subnet {{ resources.spark_on_aks.vnet.subnet_name }} associate with {{ resources.spark_on_aks.vnet.name }}"
    - name: "Create subnet my_subnet associate with {{ resources.spark_on_aks.vnet.name }}"
      azure_rm_subnet:
        resource_group: "{{ resources.spark_on_aks.rg_name }}"
        virtual_network_name: "{{ resources.spark_on_aks.vnet.name }}"
        name: "{{ resources.spark_on_aks.vnet.subnet_name }}"
        address_prefix_cidr: "10.1.0.0/24"
        service_endpoints:
          - service: Microsoft.SQL
        state: present
```

[Logs of the correct analysis](https://github.com/Checkmarx/kics/files/7392370/correct_analysis.txt)

### Specifications
(N/A if not applicable)

-   Version: 1.4.5
-   Platform: Ansible
-   Subsystem: N/A

Please reach out if anything is not clear !
