### ISSUE TITLE
Passwords and Secrets mechanism does not exclude defined variables references in the results

### ISSUE THREAD

**Issue by rafaela-soares** [Checkmarx/kics#4440]
There are a few cases related to defined variables that Password and Secrets return FP's:
- **Code snippets**:
```
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-CdnViewerRequest'
      Code:
        ZipFile: !Sub |
          function msg(password) {
            return {"password": password}
          }
```

- **CloudFormation Parameters Reference**
```
Parameters: 
  MyToken: 
    Default: None
    Description: "My Token"
    Type: String
Resources:
  myFunction: 
      Type: "AWS::Serverless::Function"
      Properties: 
        CodeUri: ./slack.zip
        Environment: 
          Variables: 
            SLACK_TOKEN: MyToken
```

- **K8s Secret Kind Reference**
```
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: kubernetes.io/service-account-token
---
apiVersion: sql.arcdata.microsoft.com/v1
kind: SqlManagedInstance
metadata:
  name: my-sql
spec:
  security: 
    adminLoginSecret: my-secret
```

### Expected Behavior
0 results

### Actual Behavior
3 result

### Steps to Reproduce the Problem

1.  Run KICS against these three samples
2.  Check results

-   Version: Development
-   Platform: CloudFormation and Kubernetes
-   Subsystem: Windows
