### ISSUE TITLE
ansible: ec2 security group based on dns lookup

### ISSUE THREAD

**Issue by markuman** [Checkmarx/kics#4631]
### Expected Behavior

(Which results are expected from KICS?)

### Actual Behavior

> File: roles/security_groups/tasks/redis.yml
> Line 27
> Expected: 'ec2_group.rules.cidr_ip' is one of [10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12] Found: 'ec2_group.rules.cidr_ip' is [{{ lookup('dig', 'some.api.domain') }}/32]
> 26 - 6379
> 27 cidr_ip: "{{ lookup('dig', 'some.api.domain' }}/32"
> 28 rule_desc: some.api.domain

### Steps to Reproduce the Problem

```yml
- name: redis test security group
  ec2_group:
    name: my-redis-sg
    description: redis security group
    region: eu-central-1
    state: present
    vpc_id: "{{ VPC }}"
    rules:
      - proto: tcp
        ports:
          - 6379
        cidr_ip:  "{{ lookup('dig', 'some.api.domain') }}/32"
        rule_desc: some.api.domain
    rules_egress: []
    tags:
      Name: my-redis-sg

```

### Specifications
(N/A if not applicable)

-   Version: 1.4.9
-   Platform:
-   Subsystem:
