### ISSUE TITLE
kics-scan disable is ignored for generic password

### ISSUE THREAD

**Issue by markuman** [Checkmarx/kics#4653]
### Expected Behavior

kics ignores .yml file for query rule 487f4be7-3fd9-4506-a07a-eae252180c08

### Actual Behavior

```
Passwords And Secrets - Generic Password, Severity: HIGH, Results: 3
Description: Query to find passwords and secrets in infrastructure code.
Platform: Common

        [1]: test.yml:6

                005:   set_fact:
                006:     password: "aA1+{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits,punctuation') }}"
                007:     no_log: True
```

### Steps to Reproduce the Problem

```yml
# false-positiv - passwords here are safe and auto-generated
# Passwords And Secrets - Generic Password, Severity: HIGH, Results: 3
# kics-scan disable=487f4be7-3fd9-4506-a07a-eae252180c08
- name: generate password
  set_fact:
    password: "aA1+{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits,punctuation') }}"
    no_log: True
```

### Specifications
(N/A if not applicable)

-   Version: 1.4.9
-   Platform: common
-   Subsystem:
