### ISSUE TITLE
ansible: kics-scan ignore-line does not work as expected

### ISSUE THREAD

**Issue by markuman** [Checkmarx/kics#4661]
### Expected Behavior

No high vulnerables

### Actual Behavior

high vulnerables available

```
Default Security Groups With Unrestricted Traffic, Severity: HIGH, Results: 1
Description: Check if default security group does not restrict all inbound and outbound traffic.
Platform: Ansible

        [1]: example.yml:19

                018:             # kics-scan ignore-line
                019:             cidr_ip: 0.0.0.0/0
                020:             rule_desc: hello world
```

### Steps to Reproduce the Problem

```yml
---
- hosts: localhost
  
  tasks:
    - name: public loadbalancer sg
      ec2_group:
        name: my-public-loadbalancer
        description: security group to allow traffic from and to public loadbalancer
        region: eu-central-1
        state: present
        vpc_id: "{{ VPC }}"
        rules:
          - proto: tcp
            ports:
              - 80
              - 443
            # public ALB 80 + 443 must be access able from everywhere
            # kics-scan ignore-line
            cidr_ip: 0.0.0.0/0
            rule_desc: hello world
        rules_egress:
          - proto: all
            # kics-scan ignore-line
            cidr_ip: 10.0.0.0/8
            rule_desc: my internal network
```

### Specifications
(N/A if not applicable)

-   Version: 1.4.9
-   Platform: ansible
-   Subsystem:
