### ISSUE TITLE
Bug: ServiceType is NodePort on Secret resource

### ISSUE THREAD

**Issue by adberger** [Checkmarx/kics#4896]
### Expected Behavior

no **Service** error/violation for a **Secret** resource.

### Actual Behavior

```
Service Type is NodePort, Severity: LOW, Results: 1
Description: Service type should not be NodePort
Platform: Kubernetes
	[1]: templated/chart.yaml:222
		221:     app.kubernetes.io/component:  ingress
		222: type: Opaque
		223: data:
```

```
...
---
# Source: chart/templates/ingress/tls-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-ingress-tls
  labels:
    app.kubernetes.io/name: chart
    helm.sh/chart: chart-3.2.2-manually
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "RELEASE-NAME"
    app.kubernetes.io/version: ""
    app.kubernetes.io/component:  ingress
type: Opaque
data:
  tls.crt: "redacted"
  tls.key: "redacted"
...
```

### Specifications

-   Version: v1.5.2
-   Platform: Docker Image (checkmarx/kics:latest)
-   Subsystem: https://github.com/Checkmarx/kics/blob/master/assets/queries/k8s/service_type_is_nodeport/query.rego
