### ISSUE TITLE
How to use docker image for kics pre-commit hooks?

### ISSUE THREAD

**Issue by tspearconquest** [Checkmarx/kics#5022]
**Is your feature request related to a problem? Please describe.**
The v1.5.2 release deprecated binaries and recommended moving to docker. That's great, I'd love to. I'm on a Mac and I already use docker daily.

So I went to the docs site to look for the updated instructions, and made sure I'm on the v1.5.4 version of the docs:
https://docs.kics.io/latest/integrations_pre_commit/

So I'm looking and... It doesn't say anything about using docker in this case. Am I expected to make script in my path called `kics` in order to run `docker run --rm -v /path/to/some/dir:/tmp -t kics:latest` or whatever?

**Describe the solution you'd like**
I'd really like to upgrade because v1.5.1 seems to have a bug I can't currently get around and we have kics in our pre-commit hooks. But the pre-commit hooks at v1.5.4 seem to still use my binary from v1.5.1 since I can't upgrade it on homebrew. And there's no documentation covering this presently, so maybe if you could please add that first, and then help me if I have troubles once the docs exist, that would be wonderful.

**Describe alternatives you've considered**
Tried to figure out how to make pre-commit use docker, but failed.

**Additional context**
I can't wait to try this out, so please let me know if I can help somehow. I don't mind writing the docs if you have some instructions somewhere.

**Comment by lipeavelar** [comment]
Hello, @tspearconquest, I think [using docker_image language][1] can solve your issue while docs are not updated. 🙂 

[1]: https://[pre-commit](https://pre-commit.com/#docker_image).com/#docker_image

**Comment by joaorufi** [comment]
Hi @tspearconquest, thank you for contacting us!

There is a [PR](https://github.com/Checkmarx/kics/pull/5031) to fix the docs and to create the kics pre-commit hook.

Meanwhile, you can use [docker_image](https://pre-commit.com/#docker_image) language to create your own local hook, as @lipeavelar said. Here is an example:
```yaml
repos:
    - repo: local
      hooks:
          - id: kics-scan-local
            name: Kics scan
            language: docker_image
            entry: checkmarx/kics scan -p /src --no-progress
            verbose: true
```

**Comment by joaorufi** [comment]
Actually, by reading pre-commit docs, they already set the image workdir to `/src`, so you can run as you said and even without the `-w` flag.

Example:
```yaml
repos:
    - repo: local
      hooks:
          - id: kics-scan-local
            name: Kics scan
            language: docker_image
            entry: checkmarx/kics scan -p . --no-progress
            verbose: true
```
