### ISSUE TITLE
Rule s3_static_website_host_enabled. Problem with AccessControl

### ISSUE THREAD

**Issue by uripb** [Checkmarx/kics#5049]
Hello,

I have a problem with the rule "s3_static_website_host_enabled" when I create an S3 bucket using cdk.

I set the "AccessControl" attribute to private (default value) but the rule fails me because it's different from null. Since "Private" is its default value and it is not public, I think you should accept the value.

We are using Kics v1.5.3.

CDK example code:

```typescript
const bucket = new Bucket(scope, 'samplePublicBucket', {
    bucketName: 'sample-bucket',
    publicReadAccess: false,
    encryption: BucketEncryption.KMS,
    bucketKeyEnabled: true,
    accessControl: BucketAccessControl.PRIVATE,
    blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
    enforceSSL: true,
    removalPolicy: RemovalPolicy.RETAIN
});
```

CloudFormation output:

```yaml
...
  "samplePublicBucket1E4B7725": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "AccessControl": "Private",
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "BucketKeyEnabled": true,
              "ServerSideEncryptionByDefault": {
                "KMSMasterKeyID": {
                  "Fn::GetAtt": [
                    "samplePublicBucketKeyD613AA4A",
                    "Arn"
                  ]
                },
                "SSEAlgorithm": "aws:kms"
              }
            }
          ]
        },
        "BucketName": "sample-bucket",
        "PublicAccessBlockConfiguration": {
          "BlockPublicAcls": true,
          "BlockPublicPolicy": true,
          "IgnorePublicAcls": true,
          "RestrictPublicBuckets": true
        },
       "UpdateReplacePolicy": "Retain",
      "DeletionPolicy": "Retain",
      "Metadata": {
        "aws:cdk:path": "stack-test/samplePublicBucket/Resource"
      }
    },
...
```

### Expected Behavior

I expect Kics to accept null and "Private" value for "AccessControl" . Two values are valid and equivalent.

### Actual Behavior

When we analyze it with Kics we get:

```
S3 Static Website Host Enabled, Severity: HIGH, Results: 1
Description: It's dangerous disabling a block public access settings in bucket or writing a bucket policy that grants public read access
Platform: CloudFormation
```

Thanks.
