### ISSUE TITLE
Ansible include causes kics to ignore it's ignore patterns

### ISSUE THREAD

**Issue by sluetze** [Checkmarx/kics#5685]
### Description
I have include statements in my ansible-playbooks. In one of my tasks of the top-playbook, there is a `create_password` parameter which triggers the generic password rule. I wanted to ignore this error, since it's a false positiv. But KICS ignores the ignore-lines.

Top-Playbook:
```yaml 
---
# test for kics ignore
# kics-scan ignore

- name: Playbook to Create users and Projects in Openstack
  hosts: localhost
  collections:
    - openstack.cloud
  environment:
    OS_PASSWORD: "{{ openstack_environment.pass }}"
    OS_AUTH_URL: "{{ openstack_environment.auth_url }}"
    OS_USERNAME: "{{ openstack_environment.username }}"
    OS_PROJECT_ID: "{{ openstack_environment.project_id }}"
    OS_PROJECT_NAME: "{{ openstack_environment.project_name }}"
    OS_USER_DOMAIN_NAME: "{{ openstack_environment.user_domain_name }}"
    OS_PROJECT_DOMAIN_ID: "{{ openstack_environment.project_domain_id }}"
    OS_REGION_NAME: "{{ openstack_environment.region_name }}"
    OS_INTERFACE: "{{ openstack_environment.interface }}"
    OS_IDENTITY_API_VERSION: "{{ openstack_environment.identity_api_version }}"
  tasks:
    - name: 'Ensure Projects are as defined'
      include: subroutines/debug.yml

    # kics-scan ignore-block
    - name: 'Create Users in Openstack'
      openstack.cloud.identity_user:
        state: present
        name: "{{ add_user.name }}"
        password: "{{ all_openstack_default_pass }}"
        email: "{{ add_user.email }}"
        # kics-scan ignore-line
        update_password: on_create
        default_project: "{{ add_user.orgunit }}"
        domain: default
      loop: "{{ users_present }}"
```

subroutines/debug.yml
```yaml
#---
#- name: 'this is a task'
#  debug:
#    msg: 'this is an output'
```
yes this is all commented. It doesn't make a difference what content this file has. It's enough that this file exists.

The result is 
```bash
Scanning with Keeping Infrastructure as Code Secure v1.5.13



Files scanned: 25
Parsed files: 24
Queries loaded: 281
Queries failed to execute: 0

------------------------------------

Passwords And Secrets - Generic Password, Severity: HIGH, Results: 2
Description: Query to find passwords and secrets in infrastructure code.
Platform: Common

	[1]: ../../path/openstack-users-and-projects.yml:42

		041:         email: "{{ add_user.email }}"
		042:         update_password: on_create
		043:         default_project: "{{ add_user.orgunit }}"


	[2]: ../../path/test-kics.yml:32

		031:         # kics-scan ignore-line
		032:         update_password: on_create
		033:         default_project: "{{ add_user.orgunit }}"
```

|Testcase|Result|
|---|---|
|include statement points to existing valid file|ignore is not effective|
|include statement points to existing empty file|ignore is not effective|
|include statement points to nonexisting file|ignore is effective|
|include statement is missing|ingore is effective|

This seems to be true for every ignore-scope (file, block, line).

### Expected Behavior
I expect kics to ignore the error and respect the comment

### Actual Behavior
Kics ignores the ignore statement
(Formatted logs and samples helps us to better understand the issue)

### Steps to Reproduce the Problem

(Command line arguments and flags used)
1. `mkdir -p subroutines && touch subroutines/debug.yml
2. copy my root-playbook
3. run kics on the folder including the examples provided `podman run -it -v $PWD:/path checkmarx/kics:latest scan -p "/path" --log-level=DEBUG`
4. kics errors
5. remove include task OR `rm subroutines/debug.yml`
6. run kics
7. kics successfully ignores the update_password

### Specifications
(N/A if not applicable)

-   Version: v1.5.13
-   Platform: ubuntu linux / podman
-   Subsystem: N/A
