### ISSUE TITLE
Issues using `kics-scan` hook

### ISSUE THREAD

**Issue by tspearconquest** [Checkmarx/kics#5968]
Hello, I have been using an older release of KICS (the 1.5.4 binary release from Homebrew) via the pre-commit hook until yesterday.

```
- repo: https://github.com/Checkmarx/kics
  rev: 'v1.5.4' # change to correct tag or sha
  hooks:
  - id: kics
    entry: kics scan --config .kics-config.yaml
```

Yesterday I switched to the docker hook and I ran into some issues

```
- repo: https://github.com/Checkmarx/kics
  rev: 'v1.6.2' # change to correct tag or sha
  hooks:
  - id: kics-scan
    entry: kics scan -p /src --config /src/.kics-config.yaml --no-progress
```

### Expected Behavior

- Docker image when using pre-commit with a named version should always work, not fail because Alpine decided to remove an old git binary package from the APK repo.
- KICS Docker release should scan fast like the Mac release

### Actual Behavior

1. The hook environment cannot be setup:
    ```
    executor failed running [/bin/sh -c wget https://releases.hashicorp.com/terraform/1.2.3/terraform_1.2.3_linux_amd64.zip     && unzip terraform_1.2.3_linux_amd64.zip && rm terraform_1.2.3_linux_amd64.zip     && mv terraform /usr/bin/terraform     && wget https://releases.hashicorp.com/terraform-provider-azurerm/3.18.0/terraform-provider-azurerm_3.18.0_linux_amd64.zip     && wget https://releases.hashicorp.com/terraform-provider-aws/3.72.0/terraform-provider-aws_3.72.0_linux_amd64.zip     && wget https://releases.hashicorp.com/terraform-provider-google/4.32.0/terraform-provider-google_4.32.0_linux_amd64.zip     && unzip terraform-provider-azurerm_3.18.0_linux_amd64.zip && rm terraform-provider-azurerm_3.18.0_linux_amd64.zip    && unzip terraform-provider-google_4.32.0_linux_amd64.zip && rm terraform-provider-google_4.32.0_linux_amd64.zip     && unzip terraform-provider-aws_3.72.0_linux_amd64.zip && rm terraform-provider-aws_3.72.0_linux_amd64.zip     && mkdir ~/.terraform.d && mkdir ~/.terraform.d/plugins && mkdir ~/.terraform.d/plugins/linux_amd64 && mv terraform-provider-aws_v3.72.0_x5 terraform-provider-google_v4.32.0_x5 terraform-provider-azurerm_v3.18.0_x5 ~/.terraform.d/plugins/linux_amd64     && apk upgrade --no-cache pcre2     && apk add --no-cache     git=2.36.2-r0]: exit code: 1
    ```
    - I was able to work around this by switching to the commit hash for where `master` points right now.
    ```
    - repo: https://github.com/Checkmarx/kics
      rev: '5103adf' # change to correct tag or sha
      hooks:
      - id: kics-scan
        entry: kics scan -p /src --config /src/.kics-config.yaml --no-progress
    ```
     - Query: The Alpine team regularly removes outdated packages from their repo and this breaks the initial environment setup for the `kics-scan` pre-commit hook, so can you please consider to EITHER un-pin the git binary so that `apk` can download the latest release, OR consider to switch to something other than Alpine for the docker image? It doesn't appear we have a choice as the end-user to pick the UBI image when using KICS in `pre-commit` so this is a frustrating experience.
2. The other issue I found is that when scanning a repo with the docker image, it takes 5x as long as scanning with the older Mac release.
    - Scan with Mac version `v1.5.4`: `Scan duration: 31.0297317s`
    - Scan with Docker version `5103adf`: `Scan duration: 2m38.340039302s`

### Steps to Reproduce the Problem

Detailed above
