### ISSUE TITLE
PANIC error when generating kics report

### ISSUE THREAD

**Issue by rahulpadhye** [Checkmarx/kics#6066]
I have been experiencing this error consistently. The scan works successfully but fails when generating report.

## CI job log

```
......
Results Summary:
HIGH: 4
MEDIUM: 8
LOW: 8
INFO: 0
TOTAL: 20
5:57AM INF Files scanned: 4
5:57AM INF Lines scanned: 143
5:57AM INF Parsed files: 3
5:57AM INF Lines parsed: 143
5:57AM INF Queries loaded: 790
5:57AM INF Queries failed to execute: 0
5:57AM INF Inspector stopped
5:57AM INF Results saved to file /<path.to.my.project>/iac-security-scan-result.json fileName=iac-security-scan-result.json
Results saved to file /<path.to.my.project>/iac-security-scan-result.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaffb28]
goroutine 1 [running]:
github.com/Checkmarx/kics/internal/console/helpers.GenerateReport({0x7ffe89ac4a57, 0x5d}, {0x7ffe89ac4ac3, 0x18}, {0x2143680, 0xc0014b0d80}, {0xc000b0cd80, 0x2, 0x0?}, {0x1})
	/app/internal/console/helpers/helpers.go:113 +0x2e8
github.com/Checkmarx/kics/pkg/scan.printOutput({0x7ffe89ac4a57, 0x5d}, {0x7ffe89ac4ac3, 0x18}, {0x2143680, 0xc0014b0d80}, {0xc000b0cd80, 0x2, 0x2}, {0x1})
	/app/pkg/scan/post_scan.go:90 +0x1d4
github.com/Checkmarx/kics/pkg/scan.(*Client).resolveOutputs(0xc000ca00a0, 0x3?, {{0xc0014d2498?, 0xc000cbc900?, 0x0?}}, 0x0?, 0x1?, {0xc0?})
	/app/pkg/scan/post_scan.go:72 +0x1b0
github.com/Checkmarx/kics/pkg/scan.(*Client).postScan(0xc000ca00a0, 0x2c12af8?)
	/app/pkg/scan/post_scan.go:112 +0x2a6
github.com/Checkmarx/kics/pkg/scan.(*Client).PerformScan(0xc000ca00a0, {0x2c12af8, 0xc00012c000})
	/app/pkg/scan/client.go:93 +0x7e
github.com/Checkmarx/kics/internal/console.executeScan(0x25f0001?)
	/app/internal/console/scan.go:163 +0xbd
github.com/Checkmarx/kics/internal/console.run(0x0?)
	/app/internal/console/scan.go:98 +0x1fe
github.com/Checkmarx/kics/internal/console.NewScanCmd.func2(0xc000bdcc00?, {0x25de8b0?, 0x11?, 0x12?})
	/app/internal/console/scan.go:43 +0x19
github.com/spf13/cobra.(*Command).execute(0xc000bdcc00, {0xc0001426c0, 0x11, 0x12})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000bdc900)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/Checkmarx/kics/internal/console.Execute()
	/app/internal/console/kics.go:90 +0xae
main.main()
	/app/cmd/console/main.go:12 +0x19
```

## CI function  snippet
```
variables:
    REPORT_NAME: "kics-result"
    FAIL_ON: "high"
    IGNORE_CODE: "results" 
    REPORT_FORMAT: "json"
.kics_scan:
  stage: test
  image:
    name: checkmarx/kics:latest
    entrypoint: [""]
  script:
    - cd $CI_PROJECT_DIR
    - kics scan -q /app/bin/assets/queries -p $CI_PROJECT_DIR --fail-on $FAIL_ON --ignore-on-exit $IGNORE_CODE -o ${PWD} --output-name $REPORT_NAME --report-formats $REPORT_FORMAT -v --no-progress 
    - cat $REPORT_NAME
  artifacts:
    reports:
      sast: $REPORT_NAME
    when: always
```

## CI YML file
```
stages:
  - tmo
  - test

kics-scan:
  stage: test
  extends: .kics_scan
  variables:
    REPORT_NAME: "iac-security-scan-result"
```
