### ISSUE TITLE
skip/ignore/suppress resources for AWS CloudFormation

### ISSUE THREAD

**Issue by tblinux** [Checkmarx/kics#6433]
I want to skip the scan or ignore one particular rule from the below security group resource. 

```
Resources:
  DemoSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref myVPC
      GroupDescription: Ports open to the world
      SecurityGroupIngress:
        - Description: Allowing port 22 for everyone
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - Description: Allowing port 80 for everyone
          # kics-scan ignore-block 
          # I want to skip this rule
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
```

I tried it by adding commands in the command `# kics-scan ignore-line` or `# kics-scan ignore-block` but it is not working. I am not sure whether I am using it right. 

At the end of this [doc](https://docs.kics.io/latest/running-kics/#using_commands_on_scanned_files_as_comments) and it says, Currently, KICS supports this feature for:

Dockerfile;
HCL (Terraform);
YAML;

Suppressing resources/configuration is still not supported for CloudFormation with KICS Scan ? If it's supported, Can anyone please help me on this ?

Thank you.
