### ISSUE TITLE
Update Security Groups With Exposed Admin Ports query for CloudFormation

### ISSUE THREAD

**Issue by tblinux** [Checkmarx/kics#6445]
### Platform
CloudFormation

### Provider
AWS

### Query ID 
cdbb0467-2957-4a77-9992-7b55b29df7b7

### Description
Query Security Groups With Exposed Admin Ports should be updated to provide accurate results when specific IP (i.e. 1.2.3.4/32) or specific IP Range is used (192.168.1.0/24).

Here's the CloudFormation Template:

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow http to client host
        VpcId:
          Ref: myVPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 11.22.33.44/32
```

### Actual Behavior
```
Security Groups With Exposed Admin Ports, Severity: HIGH, Results: 1
Description: Security Groups should not have ports open in (20, 21, 22, 23, 115, 137, 138, 139, 2049, 3389)
Platform: CloudFormation
Learn more about this vulnerability: https://docs.kics.io/latest/queries/cloudformation-queries/aws/cdbb0467-2957-4a77-9992-7b55b29df7b7

	[1]: testsg.yaml:9

		008:           Ref: myVPC
		009:         SecurityGroupIngress:
		010:         - IpProtocol: tcp
```
### Expected Behavior

It should only result in **HIGH** when 0.0.0.0/0 used for incoming traffic with exposed Admin Ports.
