### ISSUE TITLE
The Rego Playground with CloudFormation: rego_type_error: undefined function 

### ISSUE THREAD

**Issue by tblinux** [Checkmarx/kics#6446]
### Test
I am trying to test following rego policy with CloudFormation input using the rego playground, It is complaining about undefined function. 

I have tried using the default policies as a sample but result is same. 

```
package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	docs := input.document[i]
	[path, Resources] := walk(docs)
	resource := Resources[name]
	ports := [20, 21, 22, 23, 115, 137, 138, 139, 2049, 3389]

	check_security_groups_ingress(resource.Properties, ports)

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("%s%s.Properties.SecurityGroupIngress", [cf_lib.getPath(path), name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("None of the Resources.%s.Properties.SecurityGroupIngress should have an exposed port", [name]),
		"keyActualValue": sprintf("One of the Resources.%s.Properties.SecurityGroupIngress has a exposed port (20,21,22,23,115,137,138,2049,3389)", [name]),
	}
}

check_security_groups_ingress(group, ports) {
	some p
	group.SecurityGroupIngress[_].FromPort == ports[p]
}

check_security_groups_ingress(group, ports) {
	some p
	group.SecurityGroupIngress[_].ToPort == ports[p]
}
```

### Expected Behavior

In the output, the results should be as expected when input is valid.

### Actual Behavior

```
2 errors occurred:
policy.rego:16: rego_type_error: undefined function data.generic.cloudformation.get_resource_name
policy.rego:17: rego_type_error: undefined function data.generic.cloudformation.getPath
```

### Steps to Reproduce the Problem

1.  Open https://play.openpolicyagent.org/
2.  Copy & Paste the following document in the Playground
```
package Cx

import data.generic.cloudformation as cf_lib

CxPolicy[result] {
	docs := input.document[i]
	[path, Resources] := walk(docs)
	resource := Resources[name]
	ports := [20, 21, 22, 23, 115, 137, 138, 139, 2049, 3389]

	check_security_groups_ingress(resource.Properties, ports)

	result := {
		"documentId": input.document[i].id,
		"resourceType": resource.Type,
		"resourceName": cf_lib.get_resource_name(resource, name),
		"searchKey": sprintf("%s%s.Properties.SecurityGroupIngress", [cf_lib.getPath(path), name]),
		"issueType": "IncorrectValue",
		"keyExpectedValue": sprintf("None of the Resources.%s.Properties.SecurityGroupIngress should have an exposed port", [name]),
		"keyActualValue": sprintf("One of the Resources.%s.Properties.SecurityGroupIngress has a exposed port (20,21,22,23,115,137,138,2049,3389)", [name]),
	}
}

check_security_groups_ingress(group, ports) {
	some p
	group.SecurityGroupIngress[_].FromPort == ports[p]
}

check_security_groups_ingress(group, ports) {
	some p
	group.SecurityGroupIngress[_].ToPort == ports[p]
}

```
3.  In the Input, Copy & Paste the following payload
```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow ssh to client host
        VpcId:
          Ref: myVPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
          Description: "Allowing ssh Port to the internet"
```
4. Click on Evaluate

### Specifications

-   Version: N/A
-   Platform: CloudFormation
-   Subsystem: N/A
