### ISSUE TITLE
No issues detected when multiple comments on CloudFormation

### ISSUE THREAD

**Issue by LirycR** [Checkmarx/kics#6466]
### Actual Behavior

Multiple comments breaks detection on CloudFormation.

### Steps to Reproduce the Problem

Scanning the following YAML code won't detect issues because of the comments.

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Test

Resources:
  ################################
  #####      SomeTitle       #####
  ################################
  TestName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: Test

Outputs:
  TestEndpoint:
    Description: Test
```

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Test

Resources:
  ##
  TestName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: Test

Outputs:
  TestEndpoint:
    Description: Test
```

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Test

Resources:
  TestName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: Test

###############################
####      SomeTitle       #####
###############################
Outputs:
  TestEndpoint:
    Description: Test
```

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Test

Resources:
  TestName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: Test

#######
Outputs:
  TestEndpoint:
    Description: Test
```
