### ISSUE TITLE
Query Kubernetes "Volume Mount With OS Directory Write Permissions" not working correctly 

### ISSUE THREAD

**Issue by felipeng** [Checkmarx/kics#6598]
Depending of the `mountPath` value the query "Volume Mount With OS Directory Write Permissions" (b7652612-de4e-4466-a0bf-1cd81f0c6063) identify the issue

### Steps to Reproduce the Problem

1. Create a new helm-chart: `helm create test`
2. Add volumes on  `test/templates/deployment.yaml`:
```
          volumeMounts:
          - name: dir1
            mountPath: /etc
      volumes:
      - name: dir1
        emptyDir: {}
```
3. Run kics: `kics scan -t Kubernetes -p test/  -i b7652612-de4e-4466-a0bf-1cd81f0c6063`

KICS identify the issue; however if you update from `mountPath: /etc` to  `mountPath: /tmp` or something else like `/dir1`, it doesn't identify the issue 

### Specifications

-   Version: 1.7.5
