### ISSUE TITLE
Ignore is not working correctly on YAML files

### ISSUE THREAD

**Issue by felipeng** [Checkmarx/kics#6599]
# Steps to Reproduce the Problem

1. Create a new helm-chart: `helm create test`
2. Add volumes on  `test/templates/deployment.yaml`:
```
          volumeMounts:
          - name: dir1
            mountPath: /var/dir1
      volumes:
      - name: dir1
        emptyDir: {}
```
3. Run kics: `kics scan -t Kubernetes -p test/  -i b7652612-de4e-4466-a0bf-1cd81f0c6063`

Test environment validated, KICS is identifying the issue

### Ignoring the whole file (not working)

1. Added the following text on the top of `test/templates/deployment.yaml`
```
---
# kics-scan ignore
```
2. Run kics: `kics scan -t Kubernetes -p test/  -i b7652612-de4e-4466-a0bf-1cd81f0c6063`
3. KICS doesn't ignore the query

### Disabling the query b7652612-de4e-4466-a0bf-1cd81f0c6063 (not working)

1. Added the following text on the top of `test/templates/deployment.yaml`
```
---
# kics-scan disable=b7652612-de4e-4466-a0bf-1cd81f0c6063
```
2. Run kics: `kics scan -t Kubernetes -p test/  -i b7652612-de4e-4466-a0bf-1cd81f0c6063`
3. KICS doesn't ignore the query

### Ignore block (partially working)

1. Added the `ignore-block` on `test/templates/deployment.yaml`
```
          # kics-scan ignore-block
          volumeMounts:
          - name: dir1
            mountPath: /var/dir1
```
2. Run kics: `kics scan -t Kubernetes -p test/  -i b7652612-de4e-4466-a0bf-1cd81f0c6063`
3. KICS ignore the query, working!
4. However if the `volumeMounts` has multiple volumes, don't work. Example:
```
          # kics-scan ignore-block
          volumeMounts:
          - name: dir1
            mountPath: /var/dir1
          - name: dir2
            mountPath: /var/dir2
      volumes:
      - name: dir1
        emptyDir: {}
      - name: dir2
        emptyDir: {}
```

# Specifications

-   Version: 1.7.5

### Specifications

-   Version: 1.7.5
