### ISSUE TITLE
bug(engine): configuration issue to detect dockerfile

### ISSUE THREAD

**Issue by mymichu** [Checkmarx/kics#6756]
We are using kics version 1.7.9 to scan our dockerfiles, and we recently discovered that if we are using the configuration below the dockerfile is discovered but not analyzed. 

```yaml
path: "."
verbose: false
type:
  - Dockerfile
queries-path: "/kics/assets/queries"
libraries-path: "/kics/assets/libraries"
log-file: false
output-path: "reports/lint-docker"
minimal-ui: true
no-progress: true
disable-full-descriptions: false
timeout: 3
report-formats: 
  - json
  - glsast
exclude-paths:
  - templates
  - ".git/config"
exclude-queries:
  - d3499f6d-1651-41bb-a9a7-de925fea487b # Unpinned Package Version in Apk Add
  - 02d9c71f-3ee8-4986-9c27-1a20d0d19bfc # Unpinned Package Version in Pip Install
  - b03a748a-542d-44f4-bb86-9199ab4fd2d5 # Healthcheck Instruction Missing
```
  
  This is the output of the scan in verbose mode:
  
```console
Scanning with Keeping Infrastructure as Code Secure v1.7.9


12:46PM INF Scanning with Keeping Infrastructure as Code Secure v1.7.9
12:46PM INF Operating system: linux
12:46PM INF Total memory: 17.6G
12:46PM INF CPU: 7.0
12:46PM INF Total files in the project: 90
12:46PM INF .gitignore file was found in 'ROOTDIR' and it will be used to automatically exclude paths
12:46PM INF Excluded file ROOTDIR/.git/FETCH_HEAD from analyzer
12:46PM INF Excluded file ROOTDIR/.git/HEAD from analyzer
12:46PM INF Excluded file ROOTDIR/.git/ORIG_HEAD from analyzer
12:46PM INF Excluded file ROOTDIR.git/config from analyzer
12:46PM INF Excluded file ROOTDIR.git/description from analyzer
12:46PM INF Excluded file ROOTDIR/.git/info/exclude from analyzer
12:46PM INF Excluded file ROOTDIR/.git/logs/HEAD from analyzer
12:46PM INF Excluded file ROOTDIR/.git/logs/refs/heads/master from analyzer
12:46PM INF Excluded file ROOTDIR/.git/logs/refs/remotes/origin/HEAD from analyzer
12:46PM INF Excluded file ROOTDIR/.git/logs/refs/remotes/origin/master from analyzer
12:46PM INF Excluded file ROOTDIR/.git/packed-refs from analyzer
12:46PM INF Excluded file ROOTDIR/.git/refs/heads/master from analyzer
12:46PM INF Excluded file ROOTDIR/.git/refs/remotes/origin/HEAD from analyzer
12:46PM INF Excluded file ROOTDIR/.git/refs/remotes/origin/master from analyzer
12:46PM INF Excluded file ROOTDIR/.gitlab-ci.yml from analyzer
12:46PM INF Excluded file ROOTDIR/Dockerfile from analyzer
12:46PM INF Excluded file ROOTDIR/deliver/.terraform/modules/modules.json from analyzer
12:46PM INF Excluded file ROOTDIR/deliver/main.tf from analyzer
12:46PM INF Excluded file ROOTDIR/deliver/outputs.tf from analyzer
12:46PM INF Excluded file ROOTDIR/deliver/variables.tf from analyzer
12:46PM INF Excluded file ROOTDIR/deliver/versions.tf from analyzer
12:46PM INF Excluded file ROOTDIR/docs/CODEOWNERS from analyzer
12:46PM INF Excluded file ROOTDIR/mockery.yaml from analyzer
12:46PM INF Excluded file ROOTDIR/openapi.yaml from analyzer
12:46PM INF Excluded file ROOTDIR/renovate.json from analyzer
12:46PM INF Excluded file ROOTDIR/scripts/test.sh from analyzer
12:46PM INF No queries were loaded
12:46PM INF No files were scanned
Files scanned: 0
Parsed files: 0
Queries loaded: 0
Queries failed to execute: 0

------------------------------------


Results Summary:
HIGH: 0
MEDIUM: 0
LOW: 0
INFO: 0
TOTAL: 0

12:46PM INF Scanned Files: 0
12:46PM INF Parsed Files: 0
12:46PM INF Scanned Lines: 0
12:46PM INF Parsed Lines: 0
12:46PM INF Ignored Lines: 0
12:46PM INF Queries loaded: 0
12:46PM INF Queries failed to execute: 0
12:46PM INF Inspector stopped
12:46PM INF Results saved to file reports/lint-docker/results.json fileName=results.json
Results saved to file reports/lint-docker/results.json
12:46PM INF Results saved to file reports/lint-docker/gl-sast-results.json fileName=gl-sast-results.json
Results saved to file reports/lint-docker/gl-sast-results.json
Scan duration: 176.885666ms
12:46PM INF Scan duration: 176.885666ms
```

If I add the Dockerfile in the path setting of the configuration file, then everything seems to work as expected (the bug #6753 is here ignored and not listed again):

Working configuration file:

```yaml
path: ".,Dockerfile"
verbose: false
type:
  - Dockerfile
queries-path: "/kics/assets/queries"
libraries-path: "/kics/assets/libraries"
log-file: false
output-path: "reports/lint-docker"
minimal-ui: true
no-progress: true
disable-full-descriptions: false
timeout: 3
report-formats: 
  - json
  - glsast
exclude-paths:
  - templates
  - ".git/config"
exclude-queries:
  - d3499f6d-1651-41bb-a9a7-de925fea487b # Unpinned Package Version in Apk Add
  - 02d9c71f-3ee8-4986-9c27-1a20d0d19bfc # Unpinned Package Version in Pip Install
  - b03a748a-542d-44f4-bb86-9199ab4fd2d5 # Healthcheck Instruction Missing
```

This is the log output with the workaround configuration:

```console

Scanning with Keeping Infrastructure as Code Secure v1.7.9


1:33PM INF Scanning with Keeping Infrastructure as Code Secure v1.7.9
1:33PM INF Operating system: linux
1:33PM INF Total memory: 17.6G
1:33PM INF CPU: 7.0
1:33PM INF Total files in the project: 93
1:33PM INF .gitignore file was found in 'ROOT_DIR' and it will be used to automatically exclude paths
1:33PM INF Excluded file ROOT_DIR/.git/FETCH_HEAD from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/HEAD from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/ORIG_HEAD from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/config from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/description from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/info/exclude from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/logs/HEAD from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/logs/refs/heads/master from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/logs/refs/remotes/origin/HEAD from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/logs/refs/remotes/origin/master from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/packed-refs from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/refs/heads/master from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/refs/remotes/origin/HEAD from analyzer
1:33PM INF Excluded file ROOT_DIR/.git/refs/remotes/origin/master from analyzer
1:33PM INF Excluded file ROOT_DIR/.gitlab-ci.yml from analyzer
1:33PM INF Excluded file ROOT_DIR/Dockerfile from analyzer
1:33PM INF Excluded file ROOT_DIR/deliver/.terraform/modules/modules.json from analyzer
1:33PM INF Excluded file ROOT_DIR/deliver/main.tf from analyzer
1:33PM INF Excluded file ROOT_DIR/deliver/outputs.tf from analyzer
1:33PM INF Excluded file ROOT_DIR/deliver/variables.tf from analyzer
1:33PM INF Excluded file ROOT_DIR/deliver/versions.tf from analyzer
1:33PM INF Excluded file ROOT_DIR/docs/CODEOWNERS from analyzer
1:33PM INF Excluded file ROOT_DIR/mockery.yaml from analyzer
1:33PM INF Excluded file ROOT_DIR/openapi.yaml from analyzer
1:33PM INF Excluded file ROOT_DIR/renovate.json from analyzer
1:33PM INF Excluded file ROOT_DIR/reports/lint-docker/gl-sast-results.json from analyzer
1:33PM INF Excluded file ROOT_DIR/reports/lint-docker/results.json from analyzer
1:33PM INF Excluded file ROOT_DIR/scripts/test.sh from analyzer
1:33PM INF Loading queries of type: dockerfile
Error: stat ROOT_DIR/assets/utils/experimental-queries.json: no such file or directory
```

### Steps to Reproduce the Problem

To run the kics scanner, I am using the following command:

```console
kics scan --config config.yaml --verbose
```

Comment: The lint stops with an error because of the bug #6753

### Specifications
-   Version: 1.7.9
-   Platform: Run in docker on mac os
