### ISSUE TITLE
query(<YAML>): kics-scan ignore-block not working

### ISSUE THREAD

**Issue by apurvakg** [Checkmarx/kics#7054]
### Platform
Kubernetes YAML files

### Description
I have a Kubernetes deployment file(YAML), where the YAMl is a bit comples, I am getting error for one line in YAML, and I want to ignore the line. I have tried both `#kics-scan ignore-line` and `#kics-scan ignore-block`  and its not working. I am not sure its because of indendation or something else. Can u help me with this. Pasting the code snipped for reference.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "some-name"
spec:
  replicas: 1
  template: 
  metadata: 
    labels: "some label"
  spec:
    volumes:
        {{- toYaml .Values.secrets.volumes | nindent 8 }}
        - name: {{ include "name" . }}-config
          configMap:
            # kics-scan ignore-line
            name: {{ include "name" . }}-config  #line causing the issue
```

**Comment by kicsbot** [comment]
Please, follow the guideline for an issue title: 

For **bug**:

`bug(<scope>): <title starting with lowercase letter>`

For **query**:

`query(<platform>): <title starting with lowercase letter>`

For **feature request**:

`feat(<scope>): <title starting with lowercase letter>`

Thank you!
*KICS Team*

**Comment by kicsbot** [comment]
Please, follow the guideline for an issue title: 

For **bug**:

`bug(<scope>): <title starting with lowercase letter>`

For **query**:

`query(<platform>): <title starting with lowercase letter>`

For **feature request**:

`feat(<scope>): <title starting with lowercase letter>`

Thank you!
*KICS Team*

**Comment by kicsbot** [comment]
Please, follow the guideline for an issue title: 

For **bug**:

`bug(<scope>): <title starting with lowercase letter>`

For **query**:

`query(<platform>): <title starting with lowercase letter>`

For **feature request**:

`feat(<scope>): <title starting with lowercase letter>`

Thank you!
*KICS Team*

**Comment by kicsbot** [comment]
Please, follow the guideline for an issue title: 

For **bug**:

`bug(<scope>): <title starting with lowercase letter>`

For **query**:

`query(<platform>): <title starting with lowercase letter>`

For **feature request**:

`feat(<scope>): <title starting with lowercase letter>`

Thank you!
*KICS Team*

**Comment by alminh** [comment]
i had also the issue when i did this with [megalinter](https://megalinter.io/latest/):
```yaml
...
# some comment
- name: foobar
   # kics-scan ignore-line
   uses: xxxxx@xx
...
```
when removing "# some comment" it worked fine.

guess kics has some issue with comments before blocks. Maybe it's sth similar.
