### ISSUE TITLE
bug(helm): rendering errors on valid charts

### ISSUE THREAD

**Issue by jghal** [Checkmarx/kics#7161]
I posted this first in [discussions](https://github.com/Checkmarx/kics/discussions/7148) but received no response.

I have a helm chart based off of https://github.com/runatlantis/helm-charts and when I try to scan with Kics (both 1.7.x in GitLab CI's IaC scan docker image and 2.1.0 in the official checkmarx/kics docker image) I get a bunch of parsing errors. To give you something reproducible, One of the files that is failing to be parsed looks like this

```yaml
{{- if .Values.repoConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "atlantis.fullname" . }}-repo-config
  labels:
    app: {{ template "atlantis.name" . }}
    chart: {{ template "atlantis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  repos.yaml: |
{{ .Values.repoConfig | indent 4 }}
{{- end -}}
```

It's a valid, deployable chart template using the [published best practice](https://helm.sh/docs/chart_best_practices/templates/).

### Expected Behavior

the chart is rendered and scanned without error.

### Actual Behavior

`4:01PM ERR failed to parse file content: /work/templates/configmap-config.yaml error="failed to parse yaml: invalid yaml"`

### Steps to Reproduce the Problem

(Command line arguments and flags used)

1.  clone [https://github.com/runatlantis/helm-charts](https://github.com/runatlantis/helm-charts/)
2.  cd into _charts/atlantis_
3.  run `docker run --rm -it -u $(id -u):$(id -u) -v $(pwd):/work -w /work checkmarx/kics scan --ci -t Kubernetes -p /work/`

### Specifications
(N/A if not applicable)

-   Version: 1.7.13, 2.1.0
-   Platform: linux
-   Subsystem: kubernetes
